### ISSUE TITLE
Ac parameter

### ISSUE THREAD

**Issue by JuanFMontesinos** [diggerdu/pytorch_audio#2]
Hi,
I was wondering what is the ac parameter which is generated in stft and requiered for istft

Thanks!

**Comment by diggerdu** [comment]
typo ac=>dc

**Comment by tachen-cs** [comment]
I don't get the meaning of the ac either, does this like the DC constraints in DCT transformation?  Can you describe this parameter more specificly?

**Comment by diggerdu** [comment]
> I don't get the meaning of the ac either, does this like the DC constraints in DCT transformation? Can you describe this parameter more specificly?

Direct Current
